config/routes.rb
Spree::Core::Engine.routes.draw do
  resources :contacts,
    :controller => 'contact_us/contacts',
    :only       => [:new, :create]
  match 'contact-us' => 'contact_us/contacts#new', :as => :contact_us
end

app/models/spree/contact_us/contact.rb
module Spree
  module ContactUs
    class Contact

      include ActiveModel::Conversion
      include ActiveModel::Validations

      attr_accessor :email, :message, :name, :subject

      validates :email,   :format => { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i },
                          :presence => true
      validates :message, :presence => true
      validates :name,    :presence => {:if => Proc.new{SpreeContactUs.require_name}}
      validates :subject, :presence => {:if => Proc.new{SpreeContactUs.require_subject}}

      def initialize(attributes = {})
        [:email, :message, :name, :subject].each do |attribute|
          self.send("#{attribute}=", attributes[attribute]) if attributes and attributes.has_key?(attribute)
        end
      end

      def save
        if self.valid?
          Spree::ContactUs::ContactMailer.contact_email(self).deliver
          return true
        end
        return false
      end

      def persisted?
        false
      end

    end
  end
end

app/controllers/spree/contact_us/contacts_controller.rb
class Spree::ContactUs::ContactsController < Spree::StoreController

  helper "spree/products"
  def create
    @contact = Spree::ContactUs::Contact.new(params[:contact_us_contact])

    if @contact.save
      if Spree::ContactUs::Config.contact_tracking_message.present?
        flash[:contact_tracking] = Spree::ContactUs::Config.contact_tracking_message
      end
      redirect_to(spree.root_path, :notice => t('spree.contact_us.notices.success'))
    else
      render :new
    end
  end

  def new
    @contact = Spree::ContactUs::Contact.new
  end

  private

  def accurate_title
    t('contact_us')
  end

end

app/views/spree/contact_us/contacts/new.html.erb
<% content_for :head do -%>
  <meta name="title" content="<%= t('contact_us') %>">
<% end -%>

<% content_for :sidebar do %>
  <% if "products" == @current_controller && @taxon %>
    <%= render :partial => "spree/shared/filters" %>
  <% else %>
    <%= render :partial => "spree/shared/taxonomies" %>
  <% end %>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @contact } %>

<h1><%= t('contact_us') %></h1>
<%= form_for @contact, :url => contacts_path, :html => { :novalidate => '' } do |f| %>
  <% if SpreeContactUs.require_name %>
    <p>
      <%= f.label :name %>
      <span class="required">*</span><br/>
      <%= f.text_field :name, class: 'required' %>
    </p>
  <% end %>
  <p>
    <%= f.label :email %>
    <span class="required">*</span><br/>
    <%= f.email_field :email, class: 'required email' %>
  </p>
  <% if SpreeContactUs.require_subject %>
    <p>
      <%= f.label :subject %>
      <span class="required">*</span><br/>
      <%= f.text_field :subject, class: 'required' %>
    </p>
  <% end %>
  <p>
    <%= f.label :message %>
    <span class="required">*</span><br/>
    <%= f.text_area :message, class: 'required' %>
  </p>
  <p>
    <%= f.submit t('submit'), :alt => t('submit'), :id => 'contact_us_contact_submit', :title => t('submit') %>
  </p>
<% end %>